name: mc
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shimmer: ^3.0.0
  flutter_svg:
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.2
  google_maps_flutter: ^2.1.1
  permission_handler:
  shared_preferences: ^2.5.3
  timeago: ^3.6.1
  mime_type: ^1.0.1
  flutter_spinkit: ^5.2.1
  chat_bubbles: ^1.6.0
  toastification: 2.0.0
  quickalert: ^1.1.0

  internet_connection_checker_plus: ^2.5.2
  connectivity_plus: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  flutter_gen_runner: null

flutter_gen:
  output: lib/global/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
   # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    lottie: true
    #===========>>>>>>>>>> Flutter Gen Code ==============>>>>>>>>>>>
    # dart pub global activate flutter_gen
    # flutter pub run build_runner build --delete-conflicting-outputs
    # dart run build_runner build


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/icons/
     - assets/images/
  #   - images/a_dot_ham.jpeg


  # example:
  fonts:
     - family: Inter
       fonts:
         - asset: assets/fonts/Inter.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
